version: '3.1'

services:
  app:
    build:
      context: .
    image: app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - app
    depends_on:
      - db
      - adminer

  db:
    image: postgres:9
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - 5432:5432
    networks:
      - app

  adminer: 
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app